export const PRIVATE_FEED_START = 'PRIVATE_FEED_START';
export const PRIVATE_FEED_STOP = 'PRIVATE_FEED_STOP';
export const PRIVATE_FEED_OPEN = 'PRIVATE_FEED_OPEN';
export const PRIVATE_FEED_CLOSE = 'PRIVATE_FEED_CLOSE';
export const PRIVATE_FEED_MESSAGE = 'PRIVATE_FEED_MESSAGE';
export const PRIVATE_FEED_SELECT = 'PRIVATE_FEED_SELECT';
export const PRIVATE_FEED_DESELECT = 'PRIVATE_FEED_DESELECT';
