export const PUBLIC_FEED_START = 'PUBLIC_FEED_START';
export const PUBLIC_FEED_STOP = 'PUBLIC_FEED_STOP';
export const PUBLIC_FEED_OPEN = 'PUBLIC_FEED_OPEN';
export const PUBLIC_FEED_CLOSE = 'PUBLIC_FEED_CLOSE';
export const PUBLIC_FEED_MESSAGE = 'PUBLIC_FEED_MESSAGE';
export const PUBLIC_FEED_SELECT = 'PUBLIC_FEED_SELECT';
export const PUBLIC_FEED_DESELECT = 'PUBLIC_FEED_DESELECT';
