import {
  ingredientsRequested,
  ingredientsReceived,
  ingredientsFailed,
  placeOrderRequested,
  placeOrderSucceed,
  placeOrderFailed,
  getOrderRequested,
  getOrderSucceed,
  getOrderFailed,
  getOrderNotFound,
  registerSucceed,
  registerFailed,
  loginSucceed,
  loginFailed,
  logoutSucceed,
  logoutFailed,
  passwordResetSucceed,
  passwordResetFailed,
  codeRequestSucceed,
  codeRequestFailed,
  profileUpdateSucceed,
  profileUpdateFailed,
  userFailed,
  refreshFailed,
  clearError,
  clearOrderNotFound,
  clearSuccess,
  wsError,
  generalAPIError,
} from './api-slice';

import {
  setForgotEmail,
  resetForgotForm,
  setLoginEmail,
  setLoginPass,
  resetLoginForm,
  setProfileName,
  setProfilePass,
  setProfileEmail,
  resetProfileForm,
  setRegisterName,
  setRegisterPass,
  setRegisterEmail,
  resetRegisterForm,
  setResetCode,
  setResetPass,
  resetResetForm,
} from './forms-slice';

import {
  PRIVATE_FEED_START,
  PRIVATE_FEED_STOP,
  PUBLIC_FEED_START,
  PUBLIC_FEED_STOP,
  startPrivateFeed,
  stopPrivateFeed,
  setPrivateFeedOpened,
  setPrivateFeedClosed,
  onPrivateFeedMessage,
  requestPrivateFeed,
  discardPrivateFeed,
  startPublicFeed,
  stopPublicFeed,
  setPublicFeedOpened,
  setPublicFeedClosed,
  onPublicFeedMessage,
  requestPublicFeed,
  discardPublicFeed,
  captureOrder,
  releaseOrder,
} from './feed-slice';

import {
  setIngredients,
  selectIngredient,
  releaseIngredient,
} from './ingredients-slice';

import {
  setBun,
  insertInterior,
  moveInterior,
  dropInterior,
  clearBurger,
  archiveOrder,
  setOrder,
} from './orders-slice';

import {
  setUser,
  resetUser,
} from './user-slice';

export {
  ingredientsRequested,
  ingredientsReceived,
  ingredientsFailed,
  placeOrderRequested,
  placeOrderSucceed,
  placeOrderFailed,
  getOrderRequested,
  getOrderSucceed,
  getOrderFailed,
  getOrderNotFound,
  registerSucceed,
  registerFailed,
  loginSucceed,
  loginFailed,
  logoutSucceed,
  logoutFailed,
  passwordResetSucceed,
  passwordResetFailed,
  codeRequestSucceed,
  codeRequestFailed,
  profileUpdateSucceed,
  profileUpdateFailed,
  userFailed,
  refreshFailed,
  clearError,
  clearOrderNotFound,
  clearSuccess,
  wsError,
  generalAPIError,
  setForgotEmail,
  resetForgotForm,
  setLoginEmail,
  setLoginPass,
  resetLoginForm,
  setProfileName,
  setProfilePass,
  setProfileEmail,
  resetProfileForm,
  setRegisterName,
  setRegisterPass,
  setRegisterEmail,
  resetRegisterForm,
  setResetCode,
  setResetPass,
  resetResetForm,
  PRIVATE_FEED_START,
  PRIVATE_FEED_STOP,
  PUBLIC_FEED_START,
  PUBLIC_FEED_STOP,
  startPrivateFeed,
  stopPrivateFeed,
  setPrivateFeedOpened,
  setPrivateFeedClosed,
  onPrivateFeedMessage,
  requestPrivateFeed,
  discardPrivateFeed,
  startPublicFeed,
  stopPublicFeed,
  setPublicFeedOpened,
  setPublicFeedClosed,
  onPublicFeedMessage,
  requestPublicFeed,
  discardPublicFeed,
  captureOrder,
  releaseOrder,
  setIngredients,
  selectIngredient,
  releaseIngredient,
  setBun,
  insertInterior,
  moveInterior,
  dropInterior,
  clearBurger,
  archiveOrder,
  setOrder,
  setUser,
  resetUser,
};
